Repository haryle/PyMake, pull requests merged in 2023-09, with the labels that each got.

#2 1 add basic ci tasks with GitHub action
  .github/workflows/github-actions-demo.yml
  PyMake/builder/cmd/__init__.py
  PyMake/builder/envs/__init__.py
  PyMake/builder/var/atom.py
  PyMake/builder/var/block.py
  PyMake/parser/parser.py
  PyMake/parser/tokens.py
  poetry.lock
  pyproject.toml
  tests/builder/var/test_atom.py
  tests/builder/var/test_section.py
  tests/builder/var/test_state.py
  tests/parser/conftest.py
  tests/parser/test_parser.py
  tests/parser/test_tokens.py
Labels: enhancement

#7 3 add env section class
  .github/workflows/github-actions-demo.yml
  PyMake/builder/envs/section.py
  PyMake/builder/var/section.py
  PyMake/parser/parser.py
  poetry.lock
  pyproject.toml
  tests/builder/env/test_section.py
  tests/parser/conftest.py
  tests/parser/test_env_parser.py
  tests/parser/test_parser.py
  tests/parser/test_var_parser.py
Labels: enhancement

#8 feat: add pre-commit
  .github/workflows/github-actions-demo.yml
  .pre-commit-config.yaml
  PyMake/builder/var/atom.py
  PyMake/builder/var/block.py
  PyMake/builder/var/section.py
  README.md
  doc/Target_Top_Level_Element.md
  poetry.lock
  pyproject.toml
  tests/builder/env/test_section.py
  tests/builder/var/test_atom.py
  tests/builder/var/test_block.py
  tests/builder/var/test_section.py
  tests/builder/var/test_state.py
  tests/parser/conftest.py
Labels: enhancement

#9 4 add cmd section class
  .gitignore
  .idea/.gitignore
  PyMake/builder/cmd/section.py
  PyMake/parser/parser.py
  tests/builder/cmd/__init__.py
  tests/builder/cmd/test_section.py
  tests/parser/conftest.py
  tests/parser/test_cmd_parser.py
Labels: enhancement

#13 10 make basic builder class
  LICENSE
  PyMake/builder/base_plugin.py
  PyMake/builder/cmd_plugin.py
  PyMake/builder/env_plugin.py
  PyMake/builder/utils/__init__.py
  PyMake/builder/utils/atom.py
  PyMake/builder/utils/block.py
  PyMake/builder/var/__init__.py
  PyMake/builder/var_plugin.py
  PyMake/main.py
  PyMake/parser/base_plugin.py
  PyMake/parser/cmd_plugin.py
  PyMake/parser/env_plugin.py
  PyMake/parser/parser.py
  PyMake/parser/utils/__init__.py
  PyMake/parser/utils/exceptions.py
  PyMake/parser/utils/states.py
  PyMake/parser/utils/tokens.py
  PyMake/parser/utils/type_alias.py
  PyMake/parser/var_plugin.py
  poetry.lock
  pyproject.toml
  tests/builder/cmd/test_section.py
  tests/builder/env/test_section.py
  tests/builder/var/test_atom.py
  tests/builder/var/test_block.py
  tests/builder/var/test_section.py
  tests/builder/var/test_state.py
  tests/parser/conftest.py
  tests/parser/test_cmd_parser.py
  tests/parser/test_env_parser.py
  tests/parser/test_tokens.py
  tests/parser/test_var_parser.py
Labels: enhancement

#32 31 refactoring simplify the build process
  .pre-commit-config.yaml
  PyMake/console/__init__.py
  PyMake/console/builder/__init__.py
  PyMake/console/builder/abc_builder.py
  PyMake/console/builder/builder.py
  PyMake/console/builder/cmd_builder.py
  PyMake/console/builder/env_builder.py
  PyMake/console/builder/var_builder.py
  PyMake/decorators.py
  PyMake/exceptions.py
  tests/console/__init__.py
  tests/console/conftest.py
  tests/console/test_builder_invalid.py
  tests/console/test_builder_valid.py
Labels: UI Feature

#35 17 provide a better way to execute commands
  PyMake.yaml
  PyMake/console/__init__.py
  PyMake/console/helpers.py
  PyMake/console/inspect.py
  PyMake/console/list.py
  PyMake/console/parser/parser.py
  PyMake/console/run.py
  PyMake/exceptions.py
  PyMake/main.py
Labels: functional feature

#37 Feat dev
  PyMake.yaml
  README.md
Labels: documentation

#47 14 execute native script written inside the yaml document
  PyMake.yaml
  PyMake/console/builder/builder.py
  PyMake/console/builder/cmd_builder.py
  PyMake/console/parser/parser.py
  PyMake/console/run.py
  PyMake/exceptions.py
  poetry.lock
  pyproject.toml
  tests/console/builder/test_cmd.py
  tests/console/parser/test_var_interpolation.py
Labels: functional feature

#51 50 pymake inspect results user bug
  PyMake.yaml
  PyMake/__init__.py
  PyMake/__version__.py
  PyMake/console/inspect.py
  PyMake/main.py
  poetry.lock
  pyproject.toml
  scripts/bump_version.py
Labels: functional feature

#54 feat: add matrix for 3.11
  .github/workflows/github-actions-demo.yml
  PyMake/__version__.py
  pyproject.toml
Labels: functional feature

#56 Feat dev
  PyMake.yaml
  PyMake/console/builder/var_builder.py
  PyMake/main.py
  tests/test_main/PyMake.yaml
  tests/test_main/__init__.py
  tests/test_main/test_main.py
Labels: bug

#59 58 design variable namespace
  doc/exceptions.md
  doc/expression.md
  doc/global_var.md
  doc/stages.md
  doc/variables.md
Labels: documentation

#60 58 design variable namespace
  doc/global_var.md
  doc/var_declaration.md
  doc/var_expansion.md
  doc/var_parsing.md
  doc/variables.md
Labels: documentation
